#!/usr/bin/python3 -cimport os, sys; os.execv(os.path.dirname(sys.argv[1]) + "/../common/pywrap", sys.argv)

#
# Copyright (C) 2026 Red Hat, Inc.
# SPDX-License-Identifier: LGPL-2.1-or-later


import netlib
import testlib


@testlib.nondestructive
@testlib.onlyImage("hostapd/NM-wifi not installed on our test image", "fedora-43")
class TestNetworkingWifi(netlib.NetworkCase):
    def setUp(self):
        super().setUp()
        m = self.machine

        # firewalld blocks local dnsmasq/hostapd
        m.execute("systemctl stop firewalld")
        self.addCleanup(m.execute, "systemctl start firewalld")

        # tell NM to ignore router and BSS interfaces
        self.write_file("/run/udev/rules.d/99-nm-wifi-test.rules", 'ENV{INTERFACE}=="wlan0*", ENV{NM_UNMANAGED}="1"',
                        post_restore_action="udevadm control --reload")
        m.execute("udevadm control --reload")

        # start fake wifi wlan0/1 pair and wait for it
        m.execute("modprobe mac80211_hwsim; while ! [ -e /sys/class/net/wlan0 ]; do sleep 0.1; done")
        self.addCleanup(m.execute, "rmmod mac80211_hwsim")

        # start hostapd with multiple BSSes
        self.write_file("/tmp/hostapd.conf", """
interface=wlan0
hw_mode=g
channel=1

# First network: WPA2-PSK
ssid=ZE WIFI!
wpa=2
wpa_passphrase=12345678

# Second network:-WPA2-PSK
bss=wlan0_0
ssid=PrivateNet
wpa=2
wpa_passphrase=secret123

# Third network: Open
bss=wlan0_1
ssid=OpenNet""")
        hostapd_pid = m.spawn("hostapd /tmp/hostapd.conf", "hostapd.log")
        self.addCleanup(m.execute, f"kill {hostapd_pid}")

        # give router ends an IP
        m.execute("until [ -e /sys/class/net/wlan0_1 ]; do sleep 0.1; done")
        m.execute("ip addr add 10.0.42.1/24 dev wlan0")
        m.execute("ip addr add 10.0.42.2/24 dev wlan0_0")
        m.execute("ip addr add 10.0.42.3/24 dev wlan0_1")

        # start DNS server
        dnsmasq_pid = m.spawn("dnsmasq --keep-in-foreground --log-queries --log-facility=- "
                              "--conf-file=/dev/null --dhcp-leasefile=/tmp/leases "
                              "--bind-interfaces --except-interface=lo "
                              "--interface=wlan0 --interface=wlan0_0 --interface=wlan0_1 "
                              "--dhcp-range=10.0.42.10,10.0.42.200", "wifi-dnsmasq.log")
        self.addCleanup(m.execute, f"kill {dnsmasq_pid}")

        # client-side interface
        self.iface = "wlan1"

    def testWifi(self):
        m = self.machine
        b = self.browser

        self.login_and_go("/network")
        b.wait_visible("#networking")

        self.wait_for_iface(self.iface, active=False)

        # Details column shows correct number of networks
        b.wait_text(f"tr[data-interface='{self.iface}'] [data-label='Details']", "3 networks")
        # Not connected to anything
        b.wait_not_present(f"tr[data-interface='{self.iface}'] .pf-m-success")

        self.select_iface(self.iface)
        b.wait_visible("#network-interface")
        self.wait_for_iface_setting("Status", "Inactive")

        # detects our three wifis
        b.wait_in_text("table[aria-label='Available networks'] tbody:first-of-type", "ZE WIFI!")
        b.wait_text("tr[data-ssid='ZE WIFI!'] th", "ZE WIFI!")
        self.assertEqual(b.get_pf_progress_value("tr[data-ssid='ZE WIFI!'] [data-label='Signal']"), 100)
        # sadly, mac80211_hwsim's data rate reporting is flaky, so just ensure at least one of our networks is correct
        b.wait_in_text("table[aria-label='Available networks']", "54 Mbps")
        b.wait_visible("tr[data-ssid='ZE WIFI!'] [data-label='Mode'] [aria-label='secured']")
        b.wait_visible("tr[data-ssid='ZE WIFI!'] button[aria-label='Connect']")
        # No known network yet
        b.wait_not_present(".nm-icon-known")

        b.wait_visible("tr[data-ssid='PrivateNet'] [data-label='Mode'] [aria-label='secured']")
        b.wait_visible("tr[data-ssid='PrivateNet'] button[aria-label='Connect']")

        b.wait_visible("tr[data-ssid='OpenNet'] [data-label='Mode'] [aria-label='open']")
        b.wait_visible("tr[data-ssid='OpenNet'] button[aria-label='Connect']")

        # Connect to OpenNet
        b.click("tr[data-ssid='OpenNet'] button[aria-label='Connect']")
        b.wait_visible("tr[data-ssid='OpenNet'] button[aria-label='Disconnect']")
        # gets a "connected" icon
        b.wait_visible("tr[data-ssid='OpenNet'] .nm-icon-connected")
        # gets an IP
        self.wait_for_iface_setting("Status", "10.0.42")
        # moves to top of table
        b.wait_in_text("table[aria-label='Available networks'] tbody:first-of-type", "OpenNet")

        # Overview shows connected network
        b.click("#network-interface nav a:contains('Networking')")
        b.wait_visible("#networking")
        b.wait_in_text(f"tr[data-interface='{self.iface}'] [data-label='Details']", "3 networks")
        b.wait_in_text(f"tr[data-interface='{self.iface}'] [data-label='Details'] .pf-v6-c-label.pf-m-success", "OpenNet")
        self.select_iface(self.iface)

        # Disconnect
        b.click("tr[data-ssid='OpenNet'] button[aria-label='Disconnect']")
        b.wait_visible("tr[data-ssid='OpenNet'] button[aria-label='Connect']")
        # icon moves to "known" state
        b.wait_visible("tr[data-ssid='OpenNet'] .nm-icon-known")
        b.wait_not_present("tr[data-ssid='OpenNet'] .nm-icon-connected")
        # loses IP
        self.wait_for_iface_setting("Status", "Inactive")
        # moves back to bottom of table
        b.wait_in_text("table[aria-label='Available networks'] tbody:nth-of-type(3)", "OpenNet")

        # Overview shows disconnected
        b.click("#network-interface nav a:contains('Networking')")
        b.wait_visible("#networking")
        b.wait_text(f"tr[data-interface='{self.iface}'] [data-label='Details']", "3 networks")
        b.wait_not_present(f"tr[data-interface='{self.iface}'] .pf-v6-c-label.pf-m-success")
        self.select_iface(self.iface)

        # Connect to ZE WIFI!
        b.click("tr[data-ssid='ZE WIFI!'] button[aria-label='Connect']")
        b.wait_in_text("#network-wifi-password-dialog", "Connect to ZE WIFI!")
        # wrong password
        b.set_input_text("#network-wifi-password-password-input", "wrong123")
        b.click("#network-wifi-password-connect")
        b.wait_visible("#network-wifi-password-connect.pf-m-in-progress")
        b.wait_visible("#network-wifi-password-connect:disabled")
        b.wait_in_text("#network-wifi-password-dialog", "Failed to connect. Check your password")
        # correct password
        b.set_input_text("#network-wifi-password-password-input", "12345678")
        b.click("#network-wifi-password-connect")
        b.wait_not_present("#network-wifi-password-dialog")

        # connects, action changes
        b.wait_visible("tr[data-ssid='ZE WIFI!'] button[aria-label='Disconnect']")
        # gets a "connected" icon
        b.wait_visible("tr[data-ssid='ZE WIFI!'] .nm-icon-connected")
        # gets an IP
        self.wait_for_iface_setting("Status", "10.0.42")

        # Disconnect
        b.click("tr[data-ssid='ZE WIFI!'] button[aria-label='Disconnect']")
        b.wait_visible("tr[data-ssid='ZE WIFI!'] button[aria-label='Connect']")
        # icon moves to "known" state
        b.wait_visible("tr[data-ssid='ZE WIFI!'] .nm-icon-known")
        b.wait_not_present("tr[data-ssid='ZE WIFI!'] .nm-icon-connected")
        # loses IP
        self.wait_for_iface_setting("Status", "Inactive")

        # NM now knows the connection and can re-connect without password query
        b.click("tr[data-ssid='ZE WIFI!'] button[aria-label='Connect']")
        # icon moves to "connected" state
        b.wait_visible("tr[data-ssid='ZE WIFI!'] .nm-icon-connected")
        b.wait_not_present("tr[data-ssid='ZE WIFI!'] .nm-icon-known")
        b.wait_visible("tr[data-ssid='ZE WIFI!'] button[aria-label='Disconnect']")
        self.wait_for_iface_setting("Status", "10.0.42")
        # OpenNet is known but not connected
        b.wait_visible("tr[data-ssid='OpenNet'] .nm-icon-known")

        # connecting to OpenNet disconnects from ZE WIFI!
        self.assertIn("ZE WIFI!", m.execute("nmcli d show wlan1 | grep GENERAL.CONNECTION"))
        b.click("tr[data-ssid='OpenNet'] button[aria-label='Connect']")
        b.wait_visible("tr[data-ssid='OpenNet'] button[aria-label='Disconnect']")
        # OpenNet icon moves to "connected" state
        b.wait_visible("tr[data-ssid='OpenNet'] .nm-icon-connected")
        b.wait_not_present("tr[data-ssid='OpenNet'] .nm-icon-known")
        # ZE WIFI! moves to "known" state
        b.wait_visible("tr[data-ssid='ZE WIFI!'] button[aria-label='Connect']")
        b.wait_visible("tr[data-ssid='ZE WIFI!'] .nm-icon-known")
        b.wait_not_present("tr[data-ssid='ZE WIFI!'] .nm-icon-connected")
        self.assertIn("OpenNet", m.execute("nmcli d show wlan1 | grep GENERAL.CONNECTION"))

        # WiFi kill switch: detected networks disappear
        m.execute("nmcli radio wifi off")
        self.addCleanup(m.execute, "nmcli radio wifi on")
        self.wait_for_iface_setting("Status", "Not available")
        b.wait_not_present("table[aria-label='Available networks']")
        b.click("#network-interface nav a:contains('Networking')")
        b.wait_text(f"tr[data-interface='{self.iface}'] [data-label='Details']", "")

        m.execute("nmcli radio wifi on")
        # NM will now connect to OpenNet or ZE WIFI! automatically, but that's not predictable
        b.wait_in_text(f"tr[data-interface='{self.iface}'] [data-label='Details']", "3 networks")
        self.select_iface(self.iface)
        b.wait_in_text("table[aria-label='Available networks']", "ZE WIFI!")
        with b.wait_timeout(30):
            self.wait_for_iface_setting("Status", "10.0.42")


if __name__ == '__main__':
    testlib.test_main()
