name: build-dist
on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          # need this to also fetch tags
          fetch-depth: 0

      - name: Install minimal build dependencies
        run: |
          sudo apt install -y gettext sassc xsltproc xmlto docbook-xsl

      # similar to create-archive in packit.yaml
      - name: Build dist
        run: |
          env AUTOGEN_CONFIGURE_ARGS='--disable-polkit --disable-ssh --disable-pcp --with-systemdunitdir=/invalid CPPFLAGS=-Itools/mock-build-env' PKG_CONFIG_PATH=tools/mock-build-env test/make_dist.py

      - name: Create dist artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: cockpit-*.tar.xz
          retention-days: 1
